spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false
      username: root
      password: root
      # Druid slf4j日志配置
      filter:
        slf4j:
          enabled: true
          statement-executable-sql-log-enable: true
          statement-execute-after-log-enabled: false
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          statement-prepare-after-log-enabled: false
          statement-prepare-call-after-log-enabled: false
          statement-parameter-set-log-enabled: false
          statement-parameter-clear-log-enable: false
          statement-execute-query-after-log-enabled: false
          statement-sql-format-option:
            pretty-format: false
logging:
  level:
    org: info
    com: info
    druid: info
    druid.sql.Statement: debug
    com.parrot: debug